load("//bzl:workspace.bzl", "csapp_workspace")
csapp_workspace()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()
