package(default_visibility = ["//visibility:public"])

cc_library(
  name = "cal_server",
  srcs = [
    "cal_server.cc"
  ],
  hdrs = [
    "cal_server.h"
  ],
  deps = [
    "//common:tools",
    "//common:tcp_server",
    "//proto:cal_cc_proto"
  ]
)

##cc_library(
##  name = "cal_client",
##  srcs = [
##    "cal_client.cc",
##  ],
##  hdrs = [
##    "cal_client.h"
##  ],
##  deps = [
##    ":tools"
##  ]
##)
